# Generated by Django 4.2.30 on 2026-05-11 02:36

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_usersecurityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=tracker.models.default_transaction_time),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='unit',
            field=models.CharField(choices=[('qty', 'Qty'), ('kg', 'Kg')], default='qty', max_length=3),
        ),
    ]
