# Generated by Django 6.0.5 on 2026-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_transactionpayment_paid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_token',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='transactionpayment',
            name='receipt_token',
            field=models.CharField(blank=True, default='', max_length=36),
            preserve_default=False,
        ),
    ]
